language: android

android:
  components:
    - android-21
    - build-tools-21.1.2

notifications:
  email:
    recipients:
      - x1210x@gmail.com
    on_success: always
    on_failure: always

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean assemble
